det_sad/conspect/urls.py
from django.urls import path
from .views import LessonView, lessons

app_name = 'conspect'


urlpatterns = [
    # path('', LessonView.as_view(), name='lessons'),
    path('', lessons, name='lessons_tmp'),
]

det_sad/det_sad/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('conspect.urls')),
]

det_sad/conspect/models.py
from django.db.models import *

# Create your models here.


class SubjectModel(Model):
    name = CharField(max_length=150, verbose_name='Название темы')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Тема'
        verbose_name_plural = 'Темы'


class AnswerModel(Model):
    subject = ForeignKey(SubjectModel, on_delete=CASCADE, verbose_name='Тема')
    text = TextField(verbose_name='Варианты ответов')

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = 'Ответ'
        verbose_name_plural = 'Ответы'


class LessonModel(Model):
    name = CharField(max_length=150, verbose_name='Название')
    subjects = ManyToManyField(SubjectModel, verbose_name='Темы')
    date_created = DateField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Конспект'
        verbose_name_plural = 'Конспекты'


class LessonJSONModel(Model):
    text = TextField()

det_sad/conspect/views.py
from django.http import HttpResponse
from django.shortcuts import render
from rest_framework.views import Response, APIView
from .models import *
from .serializers import *
# Create your views here.


class LessonView(APIView):

    def get(self, request):
        objects = LessonModel.objects.all()
        serializer = LessonSerializer(objects, many=True)
        return Response(serializer.data)

    def post(self, request):
        print(request.POST)
        serializer = LessonSerializer(data=request.data)
        serializer.create_json()
        return HttpResponse(status=201)


def lessons(request):
    objects = SubjectModel.objects.all()
    context = {'subjects': objects}
    return render(request, 'index.html', context)


det_sad/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en" id="hhh">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static '5.css' %}">

</head>

<body>
    <div class="container">
        <div class="answer-wrapper">
            <input type="button" value="Сохранить Конспект" id="save_cons">
            <input type="button" value="Скачать Конспект" id="get_cons">
            <input type="button" value="Посмотреть Конспекты" id="show_cons">
        </div>
        <div class="question-wrapper">
            <section class="questions" id="question">
                <h3 class="questions_title">Выбери подходящий для своего конспекта вариант :</h3>
                {% for subject in subjects %}
                <div class="questions_block" id="block_1"><h4 class="title_topic">{{ subject.name }}</h4>
                    {% for answer in subject.answermodel_set.all %}
                    <label class="options"><input type='checkbox' name="{{ subject }}" value="{{ answer.text }}"> {{ answer }} </label>
                    {% endfor %}
                </div>
                {% endfor %}
            </section>
            <section class="total" id="total">
                <h3 class="total_title">Результат :</h3>
                <div id="total_list"></div>
            </section>
        </div>
    </div>
    <script src="{% static '6.js' %}"></script>
</body>
</html>

det_sad/templates/lessons.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Уроки</title>
</head>
<body>

{% for lesson in lessons %}
<div style="border: 1px solid red">
    {{ lesson.name }}
    <ul>
        {% for subject in lesson.subjects.all %}
        <li>
            {{ subject.name }}
            <ul>
                {% for answer in subject.answermodel_set.all %}
                <li>{{ answer.text }}</li>
                {% endfor %}
            </ul>
        </li>
        {% endfor %}
    </ul>
</div>
{% endfor %}
</body>
</html>